### ISSUE TITLE
Hiding Spellbook tab with active spells [FoundryVTT Magic Items]

### ISSUE THREAD

**Issue by InnilToo** [illandril/FoundryVTT-sheet5e-lockdown#10]
If spell is added to a character sheet by [FoundryVTT Magic Items](https://gitlab.com/riccisi/foundryvtt-magic-items) module Spellbook tab will be hidden even if there are spells on it. Tested on with default character sheet and [Compact DnDBeyond-like 5e Character Sheet](https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet). I believe intended behavior would be to have the tab visible if there is any spell present.

![image](https://user-images.githubusercontent.com/33260912/99149808-a3c9f580-2690-11eb-991d-41e7e57ab961.png)

**Comment by illandril** [comment]
As a temporary workaround, you can add an "Ignore this spell" cantrip (or something similar) to characters who have no spells but have magic items that contain spells.

The Magic Items module does some weird things and isn't actually giving the character spells (from a technical, code standpoint), so it may take a while before I have enough time to put in a reasonable fix for this that doesn't break things for people who don't use the Magic Items module.
