### ISSUE TITLE
Give some obvious indication when sheet is locked/unlocked

### ISSUE THREAD

**Issue by GambetTV** [illandril/FoundryVTT-sheet5e-lockdown#12]
Right now in certain tabs you can't tell if the character sheet is locked or not. This is especially true when using Tidy5e Sheet, but is true even with the standard character sheet. It'd be cool if you could just change the font from Red to Green or something to indicate when it was on and off, or something similar.

**Comment by illandril** [comment]
Note: I'm open to changing what I did to fix this (changing the text, icon, and color of the toggle button). If you (or anyone else) want something different, just give let me know more specifically what you'd like changed and I'll consider it.
