### ISSUE TITLE
Feature Request: Hide Tidy5eSheet's "Journal" tab

### ISSUE THREAD

**Issue by M0nk3yy** [illandril/FoundryVTT-sheet5e-lockdown#16]
Hi illandril, thanks for this mod. I have found it great for introducing new players to the game and keeping things simple.

I find the Tidy5eSheet support works pretty much perfectly, but Tidy adds a "Journal" tab that unlike the vanilla Biography tab, can't be hidden by lockdown. Would be nice if this was possible!

**Comment by illandril** [comment]
This is something that is better done by the Tidy5eSheet module itself, and it appears sdenec is already considering doing this: https://github.com/sdenec/tidy5e-sheet/issues/347
