### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by Zarhog** [illandril/FoundryVTT-sheet5e-lockdown#17]
![image](https://user-images.githubusercontent.com/76391362/121947153-a0ddd300-cd4d-11eb-9ecb-d6fb9490247a.png)

separate each of the delete button options for more control, i want to hide my spell book if i have no spells

**Comment by illandril** [comment]
Would a separate "Hide Empty Spellbooks" setting be a good alternative to making this setting more granular?

**Hide Empty Spellbooks**
If checked, the Spellbook tab will be hidden when the character sheet is locked and the character has no spells, regardless of the Hide Add and Delete Item Buttons setting. If unchecked, the Spellbook tab for characters with no spells will be hidden or shown based on the Hide Add and Delete Item Buttons setting when the character sheet is locked.
