### ISSUE TITLE
Item edit button hidden

### ISSUE THREAD

**Issue by Zarhog** [illandril/FoundryVTT-sheet5e-lockdown#19]
![image](https://user-images.githubusercontent.com/76391362/122651330-ffc99080-d12f-11eb-9f2d-9d134321ce8d.png)

It would apear that your modual hides the item edit button. can you please fix this.?

**Comment by illandril** [comment]
Hiding the Item Edit button is a feature. If you want the Item Edit buttons to show, but not other things, you can turn that feature off by unchecking the "Hide Edit Item Buttons" setting.
