### ISSUE TITLE
Tideying up sheets

### ISSUE THREAD

**Issue by Zarhog** [illandril/FoundryVTT-sheet5e-lockdown#25]
![image](https://user-images.githubusercontent.com/76391362/128601373-75cd4571-90b1-409e-a4e3-2a93188e139e.png)
Can you please add something in this module to hide these buttons, there are most of the time useless.

**Comment by illandril** [comment]
Those buttons are added by BetterRolls5e, and it is already a configurable setting in that module. The setting is "Add Extra Roll Buttons to Sheet".
