### ISSUE TITLE
TidyNPC sheets new issue.

### ISSUE THREAD

**Issue by Bryn1701** [illandril/FoundryVTT-sheet5e-lockdown#26]
The previous post I made about the console error involving TidyNPC sheets has been fixed in the update. But unfortunately has produced another bug. This time the entire NPC character sheet is blank until you unlock the sheet.

Screenshots below:
https://gyazo.com/e6e72caf36a74b41530df5bb00367ce7
https://gyazo.com/11ad0d8abea6603822f4696fbe75580a

**Comment by illandril** [comment]
This only happens for NPCs that don't have Legendary Actions, Legendary Resistances, or Lair Actions.

FYI: I'm very close to dropping support for Tidy5e... they keep changing things around in ways that break compatibility with this module, often in ways that impact only some characters/NPCs, making it hard for me to notice the issues. On top of that, it is very, very awkward to have two sets of lock/unlock toggles, so I hate the user experience that having both modules enabled provides. I highly recommend opening issues with Tidy5e to add native support for the features that this module provides that you want but aren't already provided by Tidy5e.
