### ISSUE TITLE
[FEATURE] Locking the ability to change the available spell slots

### ISSUE THREAD

**Issue by namireki** [illandril/FoundryVTT-sheet5e-lockdown#28]
I like your mod very much! Unfortunately, I've one subtle cheater in my campaign and from time to time I had the suspicion that she would change her available spell slots behind my back. One minute she had zero 4 level spell slots and the next one she had 2. Is it possible to add another setting to lock this along with the already available Max Spell Slots Overrides?

Thanks!
Giovanni.

**Comment by illandril** [comment]
I recommend you work with your player to prevent her from wanting to cheat. She will still be able to cheat even with this field "locked" (while it will be harder, it is possible to circumvent any locking that any module can offer). Also, if she is feeling like she should cheat, her fun may be getting ruined by feeling like her character is underpowered or have other problems with resource management.

I will add this switch anyway - it will be fairly simple to add (and I see potential value in it beyond cheat prevention, so even if it wasn't simple I still might consider it).

**Comment by namireki** [comment]
Thank you very much, it works perfectly! I understand your suggestion and I usually do that but in this specific case, I prefer not to "mess" with her for personal issues. Thank again, great mod!
