### ISSUE TITLE
[FEATURE] Possibiltiy to lock LevelUp button

### ISSUE THREAD

**Issue by sasquach45932** [illandril/FoundryVTT-sheet5e-lockdown#31]
**Is your feature request related to a problem? Please describe.**
No, feature request.

**Describe the solution you'd like**
A checkbox on the configuration screen where I can enable/disable that the user can use LevelUp button.

**Describe alternatives you've considered**
N/A

**What system(s) do you want this feature to work with?**
DnD5e - Fifth Edition System

**What other modules do you use that you want to ensure work well with this feature?**
Tidy5e Sheet

**Additional context**
Added
![ksnip_20211020-200614](https://user-images.githubusercontent.com/92884040/138147501-015d7fe8-2105-4f8a-8e69-4d368a103376.png)

**Comment by illandril** [comment]
What module is the LevelUp button coming from? It's not part of Tidy5e Sheet or the DnD5e system (unless there's some setting somewhere that I'm not able to find)
