### ISSUE TITLE
Sheet not locking fields anymore in V10 which worked perfect on v9

### ISSUE THREAD

**Issue by Weskernation** [illandril/FoundryVTT-sheet5e-lockdown#36]
**Describe the bug**
Fields are not locked anymore which where locked in V9 

**Lock Basic Details:**

- **Race** _No Lock_
- **Background** _Locks_
- **Alignment** _No Lock_
- **Size** _Locks_

**Show Background To:**

- _Unclear what it does_

**Show Alignment To:**
- _Unclear what it does_

**Lock Experience:**
-  _No Lock_

**Lock Short and Long Rests:**
- _Locks_

**Lock Ability Scores:**
- _Locks_

**Lock Proficiencies:**
- _Locks_

**Lock Resources:**
- **Name** _No Lock_
- **Maximum Value** _No Lock_
- **Reset on short/long rest toggles** _No Lock_
- **Hidden when empty** _Hides_

**Lock Traits:**
- **Senses** _Locks_
- **Languages** _Locks_
- **Immunities/Resistances/Vulnerabilities** _Locks_
- **Weapon/Armor/Tool Proficiencies** _No Lock_
- **Special Trait** _Locks_

**Lock Legendary and Lair Actions:**
- _No Lock_

**Show Special Traits:**
- _Shows_

**Hide Add Item Buttons:**
- _Hides_

**Hide Delete Item Buttons:**
- _Hides_

**Hide Empty Spellbooks:**
- _Hides_

**Hide Edit Item Buttons:**
- _Hides_

**Lock Currency:**
- _No Lock_

**Lock Equip Item Toggles:**
- _Locks_

**Lock Available Item and Feature Uses:**
- _Locks_

**Lock Prepare Spell Toggles:**
- _Locks_

**Lock Available Spell Slots:**
- _No Lock_

**Lock Max Spell Slots:**
- _Locks_

**Lock Effects:**
- _Locks_

**Show Effects Tab To:**
- _Works as intended_

**Lock Other Inputs:**
- **Max HP** _No Lock_
- **Armor Class** _Locks_
- **Speed** _Locks_
- **Initiative Modifier** _Locks_
- **Spellcasting Attribute** _No Lock_

**Disable Tidy5e Sheet support:**
- _Did not test_

**Disable Other Sheet Support:**
- _Did not test_

**What steps did you take before experiencing the problem?**
1. set the preferred locked fields
2. Log in as a player (whose fields should be locked)
3. Supposed to be locked fields can still be changed by the player

**What did you expect to happen?**
The checked fields in the configuration menu to still be locked for the selected players as it did in v9

**What happened instead?**
The mentioned fields are not locked and can be edited by the players.

**Foundry Versions**
 - Version of this module: 3.00
 - Foundry Version: v10
 - System Name and Version: DnD5e - Fifth Edition System, version #.#.#
 - Browser Name and Version: google chrome

**What other modules did you have active when experiencing this issue (include both names and versions)?**
Same as in v9 (when using module "Find the culprit" no module is the cause, it says it is in the Core)

**Comment by AlbertoEE** [comment]
Yep I can confirm that as well... It was so perfect in V9

**Comment by AlbertoEE** [comment]
@Weskernation quick fix, 

1. open the module folder with any editor of your choice (E.G VSCode)
2. press [CTRL + SHIFT + F] to find in every part of the project
3. type `data.`
4. replace with system.
5. save
6. reload FoundryVTT
7. Now it should work

![image](https://user-images.githubusercontent.com/25609497/204653910-92395bc7-25c5-4f48-8769-8679b49994c1.png)

NOTE: How to find where is the module folder:
1. [WIN + R]
2. `%localappdata%\FoundryVTT\Data\modules\illandril-sheet5e-lockdown`
3. Press ENTER

**Comment by Weskernation** [comment]
@AlbertoEE 
Thank you very much for the explanation otherwise I wouldn't understand it.
36 results in 5 files
-JS lockableCharacterSheet 7x the word data.
-JS lockableNPCSheet 12x the word data.
-JS lockableSheet 12x the word data.
-JS tidy5eCommon 2x the word data.
-JS tidy5eNPC 3x the word data.

I have changed all 36x the word "data." into "system."

It worked! thank you so much. only some minor things that the players can still edit. but the major "important" ones are locked again
